on:
  push:
    branches:
      - main  # Se ejecuta solo cuando hay cambios en main
  workflow_dispatch:  # Permite ejecuciÃ³n manual

name: ğŸ” OWASP ZAP Security Scan

permissions:
  contents: read
  actions: write  # Permite subir reportes como artefactos

jobs:
  zap_scan:
    name: ğŸ” OWASP ZAP Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4

      - name: ğŸ” Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://jr4mx.github.io/estructurahtml/"  # URL del sitio a analizar
          cmd_options: "-a"

      - name: ğŸ“¤ Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: report_html
